### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [dracula/base16#2]
Hello @mikebarkmin!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by mikebarkmin** [comment]
I think it is a great idea.

**Comment by zenorocha** [comment]
Nice! Just sent you an invite to join the Dracula org, you should be able to transfer the repository now. After that, you can rename it to `base16` and make some edits to the README so it matches [the template](https://github.com/dracula/template) and also include steps on how to install it. With that I can add it to the website ;)

**Comment by zenorocha** [comment]
https://draculatheme.com/base16/ ;)
